<?php

if (__FILE__ == $_SERVER['SCRIPT_FILENAME']) { die(); }

/* 
 * NOTE: this file is for compatibility.
 * Layouts are created in the theme options and "design-{name}.php" files.
 * Content is generated by the "template-{context}.php" files.
*/

create_page_layout('author'); // context = author

?>